import { useEffect, useRef, useState } from 'react';
import sdk from '@stackblitz/sdk';
import { FileNode } from './FileTree';
import { Loader2, Monitor } from 'lucide-react';

interface StackBlitzPreviewProps {
  files: FileNode[];
  isGenerating?: boolean;
  generationProgress?: number;
}

export const StackBlitzPreview = ({ 
  files, 
  isGenerating = false, 
  generationProgress = 0 
}: StackBlitzPreviewProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isEmbedding, setIsEmbedding] = useState(false);
  const hasEmbeddedRef = useRef(false);
  const lastFilesHashRef = useRef<string>('');

  // Convert FileNode tree to flat file structure for StackBlitz SDK
  const flattenFiles = (nodes: FileNode[], basePath = ''): Record<string, string> => {
    const result: Record<string, string> = {};
    
    for (const node of nodes) {
      const fullPath = basePath ? `${basePath}/${node.name}` : node.name;
      
      if (node.type === 'folder' && node.children) {
        const children = flattenFiles(node.children, fullPath);
        Object.assign(result, children);
      } else if (node.type === 'file' && node.content !== undefined) {
        result[fullPath] = node.content;
      }
    }
    
    return result;
  };

  // Create hash of files to detect changes
  const getFilesHash = (nodes: FileNode[]): string => {
    const flatFiles = flattenFiles(nodes);
    return JSON.stringify(flatFiles);
  };

  // Embed project in StackBlitz
  const embedProject = async () => {
    if (!containerRef.current || files.length === 0) return;
    
    const currentHash = getFilesHash(files);
    if (currentHash === lastFilesHashRef.current && hasEmbeddedRef.current) {
      return; // No changes, don't re-embed
    }
    
    setIsEmbedding(true);
    lastFilesHashRef.current = currentHash;
    
    try {
      // Clear previous embed
      containerRef.current.innerHTML = '';
      
      const flatFiles = flattenFiles(files);
      
      // Get package.json content or create default
      let packageJson: any = {
        name: 'generated-app',
        private: true,
        version: '0.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'tsc && vite build',
          preview: 'vite preview'
        },
        dependencies: {
          'react': '^18.3.1',
          'react-dom': '^18.3.1'
        },
        devDependencies: {
          '@types/react': '^18.3.3',
          '@types/react-dom': '^18.3.0',
          '@vitejs/plugin-react': '^4.3.1',
          'typescript': '^5.5.4',
          'vite': '^5.4.2'
        }
      };
      
      if (flatFiles['package.json']) {
        try {
          packageJson = JSON.parse(flatFiles['package.json']);
        } catch (e) {
          console.warn('Failed to parse package.json, using default');
        }
      }
      
      // Embed the project
      await sdk.embedProject(
        containerRef.current,
        {
          title: 'Generated App',
          description: 'App generated by AI',
          template: 'node',
          files: flatFiles,
        },
        {
          height: '100%',
          openFile: 'src/App.tsx',
          view: 'preview',
          hideNavigation: false,
          hideDevTools: false,
          devToolsHeight: 150,
          theme: 'dark',
        }
      );
      
      hasEmbeddedRef.current = true;
    } catch (error) {
      console.error('StackBlitz embed error:', error);
    } finally {
      setIsEmbedding(false);
    }
  };

  useEffect(() => {
    if (files.length > 0 && !isGenerating) {
      embedProject();
    }
  }, [files, isGenerating]);

  // Show generation progress
  if (isGenerating) {
    return (
      <div className="h-full flex flex-col items-center justify-center bg-background/50 backdrop-blur-sm">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-12 h-12 animate-spin text-primary" />
          <div className="text-center">
            <p className="text-lg font-medium">Gerando projeto...</p>
            <p className="text-sm text-muted-foreground mt-1">
              {generationProgress}% concluído
            </p>
          </div>
          <div className="w-64 h-2 bg-muted rounded-full overflow-hidden">
            <div 
              className="h-full bg-primary transition-all duration-300"
              style={{ width: `${generationProgress}%` }}
            />
          </div>
        </div>
      </div>
    );
  }

  // Show no files state
  if (files.length === 0) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center text-muted-foreground">
          <Monitor className="w-16 h-16 mx-auto mb-4 opacity-50" />
          <p>Nenhum arquivo para visualizar</p>
          <p className="text-sm mt-1">Gere um projeto para ver o preview</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full w-full relative">
      {isEmbedding && (
        <div className="absolute inset-0 flex items-center justify-center bg-background/80 backdrop-blur-sm z-10">
          <div className="flex flex-col items-center gap-3">
            <Loader2 className="w-8 h-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Carregando StackBlitz...</p>
          </div>
        </div>
      )}
      <div 
        ref={containerRef} 
        className="h-full w-full"
      />
    </div>
  );
};
